language: python

python:
  - "2.7"

before_install:
  - cd src

install:
  - pip install -r requirements.txt
  - pip install python-coveralls

before_script:
  - cd mediamanager
  - ln -s settings_development.py settings_local.py
  - cd ..

script:
  - PYTHONPATH=`pwd` py.test

after_script:
  - coveralls --base_dir .. --data_file .coverage --config_file .coveragerc
